# This workflow will install Python dependencies and run tests with a single version of Python for Penn repository

name: Testing Penn

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt && pip install -e .
        pip install pytest
    - name: Test with pytest
      run: |
        pytest
